channels:
- conda-forge
- nodefaults
dependencies:
# !! you can only use single `=` to set a version. Otherwise it will break the update job
- invoke=2.2.0
- packaging
- pyyaml
# applications
- jupyterlab=4.0.6
- jupyter-collaboration=1.2.0
- nbconvert=7.8.0
- pip:
  - notebook==7.0.0b3
# extensions
- jupyter-offlinenotebook=0.2.2
- jupyterlab-fasta=3.3
- jupyterlab-geojson=3.4
# Python Kernel
- ipykernel=6.25.2
- xeus-python=0.14.3
- ipywidgets=8
- ipyleaflet=0.17.4
- altair=5.1.1
- bqplot=0.12.40
- dask=2023.9.1
- matplotlib-base=3.7.1
- pandas=2.1.0
- python=3.9
- scikit-image=0.21.0
- scikit-learn=1.3.0
- seaborn-base=0.12.2
- tensorflow=2.11.0
- sympy=1.12
- traittypes=0.2.1
# C++ Kernel
- xeus-cling=0.13.0
- xtensor=0.23.10
- xtensor-blas=0.19.2
- xwidgets=0.26.1
- xleaflet=0.16.0
# CLI tools
- pip
- vim
